import ConfigParser                                                                                                                                                                                                         
import string, os, sys                                                                                                                                                                                                      
import paramiko                                                                                                                                                                                                             
import re                                                                                                                                                                                                                   
import time,datetime                                                                                                                                                                                                        
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
def init(paras,sftpname):                                                                                                                                                                                                   
    cf = ConfigParser.ConfigParser()                                                                                                                                                                                        
    cf.read(sftpname)                                                                                                                                                                                                       
    s = cf.sections()                                                                                                                                                                                                       
    #print 'section:', s                                                                                                                                                                                                    
    for board in cf.items('downloadcfg'):                                                                                                                                                                                   
        #print board[0]+'='+board[1]                                                                                                                                                                                        
        if board[0] == 'ip_addr':                                                                                                                                                                                           
            paras[0] = board[1]                                                                                                                                                                                             
        if board[0] == 'port':                                                                                                                                                                                              
            paras[1]=board[1]                                                                                                                                                                                               
        if board[0] == 'username':                                                                                                                                                                                          
            paras[2]=board[1]                                                                                                                                                                                               
        if board[0] == 'password':                                                                                                                                                                                          
            paras[3]=board[1]                                                                                                                                                                                               
        if board[0] == 'remote_dir':                                                                                                                                                                                        
            paras[4]=board[1]                                                                                                                                                                                               
        if board[0] == 'local_dir':                                                                                                                                                                                         
            paras[5]=board[1]                                                                                                                                                                                               
    #print  ip_addr,port,username,password,remote_dir,local_dir                                                                                                                                                             
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
def getFiles(paras,file_list,endfile):                                                                                                                                                                                      
                                                                                                                                                                                                                            
    file_dict = {}                                                                                                                                                                                                          
    del file_list[:]                                                                                                                                                                                                        
    t = paramiko.Transport((paras[0], int(paras[1])))                                                                                                                                                                       
    t.connect(username = paras[2] , password = paras[3] )                                                                                                                                                                   
    sftp = paramiko.SFTPClient.from_transport(t)                                                                                                                                                                            
    try:                                                                                                                                                                                                                    
        dirlist = sftp.listdir(paras[4])                                                                                                                                                                                    
        #print "Dirlist:", dirlist                                                                                                                                                                                          
        for file in dirlist:                                                                                                                                                                                                
            if file.startswith('FF2_SMS_AB_') and file.endswith('.txt'):                                                                                                                                                         
                #print file
                file_time=file.split('.')[0].split('_')[-1]
                local_file=file_time+"_"+file[:file.index('_'+file_time)]+".txt"                                                                                                                                                                                                 
                file_list.append(local_file)                                                                                                                                                                                      
        file_list.sort()                                                                                                                                                                                                    
    except(IOError,UnboundLocalError):                                                                                                                                                                                      
        t.close()                                                                                                                                                                                                           
        getFiles(paras,file_list,endfile)                                                                                                                                                                                   
    print  "need to sftp file count: " , len(file_list)                                                                                                                                                                     
    t.close()                                                                                                                                                                                                               
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
def sftpandsplit(paras,file_list):                                                                                                                                                                                          
                                                                                                                                                                                                                            
    t = paramiko.Transport((paras[0], int(paras[1])))                                                                                                                                                                       
    t.connect(username = paras[2] , password = paras[3] )                                                                                                                                                                   
    sftp = paramiko.SFTPClient.from_transport(t)                                                                                                                                                                            
    if len(file_list)==0:                                                                                                                                                                                                   
       print "no files need to sftp"                                                                                                                                                                                        
       time.sleep(1)                                                                                                                                                                                                        
    for file in  file_list:                                                                                                                                                                                                 
        print "file=", file
        file_time=file.split('_')[0] 
        reset_name=file[len(file_time)+1:].split('.')[0]+"_"+file_time+".txt"                                                                                                                                                                                                
        remote_file='%s/%s' % (paras[4],reset_name)                                                                                                                                                                               
        locale_file='%s/%s' % (paras[5],reset_name)                                                                                                                                                                               
        try:                                                                                                                                                                                                                
            sftp.get(remote_file, locale_file)                                                                                                                                                                              
            sftp.remove(remote_file)                                                                                                                                                                                        
        except(OSError):                                                                                                                                                                                                    
            print locale_file                                                                                                                                                                                               
            continue                                                                                                                                                                                                        
        else:                                                                                                                                                                                                               
            continue                                                                                                                                                                                                        
    #file_list =  []                                                                                                                                                                                                        
    t.close()                                                                                                                                                                                                               
                                                                                                                                                                                                                            
    #data_dir='%s' % paras[5]                                                                                                                                                                                               
    #os.chdir(data_dir)                                                                                                                                                                                                     
    #output=os.popen('pwd')                                                                                                                                                                                                 
    #print output.read()                                                                                                                                                                                                    
    #                                                                                                                                                                                                                       
    #for file in  file_list:                                                                                                                                                                                                
    #    split_cmd='split -l 100000 %s %s.SPLIT.' % (file,file)                                                                                                                                                             
    #    print 'split_cmd=',split_cmd                                                                                                                                                                                       
    #    os.popen(split_cmd)                                                                                                                                                                                                
    #    move_cmd='mv %s.SPLIT.* %s/SPLIT/' % (file,paras[5])                                                                                                                                                               
    #    os.popen(move_cmd)                                                                                                                                                                                                 
    #    os.remove(file)                                                                                                                                                                                                    
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
def main(sftpname):                                                                                                                                                                                                         
    paras = [0,0,0,0,0,0,0,0]                                                                                                                                                                                               
    endfile = []                                                                                                                                                                                                            
    file_list = []                                                                                                                                                                                                          
    ori_dir = [0]                                                                                                                                                                                                           
    init(paras,sftpname)                                                                                                                                                                                                    
    print paras                                                                                                                                                                                                             
    endfile.append(paras[6])                                                                                                                                                                                                
                                                                                                                                                                                                                            
    output = os.popen('pwd')                                                                                                                                                                                                
    ori_dir[0] = output.read().rstrip()                                                                                                                                                                                     
    while True:                                                                                                                                                                                                             
        curr_time=time.strftime('%Y%m%d %H:%M:%S')                                                                                                                                                                          
        print "getFiles start:", curr_time                                                                                                                                                                                  
        getFiles(paras,file_list,endfile)                                                                                                                                                                                   
        curr_time=time.strftime('%Y%m%d %H:%M:%S')                                                                                                                                                                          
        print "getFiles end,start to sftpSrv curr_time=%s,file_len=%d" %(curr_time,len(file_list))                                                                                                                          
        sftpandsplit(paras,file_list)                                                                                                                                                                                       
        curr_time=time.strftime('%Y%m%d %H:%M:%S')                                                                                                                                                                          
        print "sftpSrv end,start to getFiles ", curr_time                                                                                                                                                                   
        #time.sleep(5)                                                                                                                                                                                                      
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
if __name__ == '__main__':                                                                                                                                                                                                  
    main('sftpsms.cfg')                                                                                                                                                                                                        

